export const content = {
  hero: {
    badge: "Comprehensive ACT Training",
    title: "ACT Test Preparation",
    subtitle: "Master the ACT with expert instruction, proven strategies, and personalized support. Achieve your target score and unlock your college potential.",
    ctas: {
      primary: "ACT Diagnostic",
      secondary: "View Programs",
    },
  },
  whyAEEG: {
    badge: "Why AEEG",
    title: "Why Choose AEEG for ACT Prep?",
    description: "We combine American expertise with a deep understanding of Egyptian students' needs to deliver unmatched ACT preparation.",
    items: [
      { title: "15+ Years Experience", description: "Since 2011, AEEG has helped thousands of students achieve their target ACT scores with a proven, data-driven approach to test preparation." },
      { title: "Proven Score Improvement", description: "Our students consistently achieve score improvements of 4–6 points on the ACT composite. Track record of success with measurable results." },
      { title: "Expert Instructors", description: "Learn from certified educators with years of ACT-specific teaching experience. Our instructors know the test inside and out." },
      { title: "Comprehensive Curriculum", description: "Our curriculum covers every section of the ACT — English, Math, Reading, and Science — with strategy-based instruction and real practice tests." },
      { title: "Personalized Plans", description: "Every student receives a customized study plan based on their diagnostic results, target score, and timeline. No two plans are the same." },
      { title: "Ongoing Support", description: "From your first diagnostic to test day, our team provides continuous feedback, progress tracking, and motivational support to keep you on track." },
    ],
  },
  programs: {
    badge: "Our Programs",
    title: "ACT Prep Programs",
    description: "Flexible learning options designed to fit your schedule, learning style, and goals. All programs include comprehensive materials and progress tracking.",
    items: [
      {
        name: "Online Tutoring",
        price: "$25",
        period: "/lesson",
        description: "Live virtual ACT prep classes from the comfort of your home.",
        features: ["Live interactive sessions", "Small group (max 6 students)", "Digital practice materials", "Progress reports", "Flexible scheduling"],
        popular: false,
        cta: "Enroll Now",
      },
      {
        name: "In-Center Private Tutoring",
        price: "$35",
        period: "/lesson",
        description: "Face-to-face ACT preparation at our Cairo center.",
        features: ["One-on-one attention", "In-person at Cairo center", "Customized study plan", "Full-length practice tests", "Detailed score analysis"],
        popular: true,
        cta: "Enroll Now",
      },
      {
        name: "Online Private Tutoring",
        price: "$40",
        period: "/lesson",
        description: "One-on-one private ACT tutoring online from anywhere.",
        features: ["Private one-on-one sessions", "Live online via secure video platform", "Fully customized curriculum", "Flexible scheduling", "Direct instructor access"],
        popular: false,
        cta: "Enroll Now",
      },
    ],
    note: "Discount packages are available. Contact us for details on multi-session savings and group rates.",
  },
  testDates: {
    badge: "Test Dates",
    title: "ACT Test Dates",
    description: "Plan your preparation with our upcoming ACT test schedule. Register early to secure your preferred test date and avoid late fees.",
    columns: { testDate: "Test Date", registrationDeadline: "Registration Deadline", lateRegistration: "Late Registration" },
    dates: [
      { date: "September 14, 2025", registration: "August 8, 2025", late: "August 25, 2025" },
      { date: "October 26, 2025", registration: "September 19, 2025", late: "October 6, 2025" },
      { date: "December 14, 2025", registration: "November 7, 2025", late: "November 24, 2025" },
      { date: "February 8, 2026", registration: "January 2, 2026", late: "January 19, 2026" },
      { date: "April 4, 2026", registration: "February 27, 2026", late: "March 16, 2026" },
      { date: "June 14, 2026", registration: "May 8, 2026", late: "May 25, 2026" },
    ],
    note: "Test dates are subject to change by ACT, Inc. Please verify dates on the official ACT website and register well in advance to avoid late fees.",
  },
  faqs: {
    badge: "FAQ",
    title: "Frequently Asked Questions",
    description: "Everything you need to know about ACT preparation at AEEG.",
    items: [
      { question: "What is the ACT test?", answer: "The ACT is a standardized test used for college admissions in the United States. It assesses high school students' readiness for college-level work and covers four subject areas: English, Mathematics, Reading, and Science, with an optional Writing section. AEEG's ACT prep program helps students master each section with targeted strategies and practice." },
      { question: "How is the ACT scored?", answer: "Each section of the ACT is scored on a scale of 1–36. Your composite score is the average of your four section scores (English, Math, Reading, Science), also on a 1–36 scale. The optional Writing section is scored separately on a scale of 2–12. Our instructors help you understand the scoring system to maximize your performance." },
      { question: "What is the difference between the ACT and SAT?", answer: "The ACT includes a Science section which the SAT does not, and its Math section covers more advanced topics including trigonometry. The ACT is also more time-pressured per question. The SAT puts more emphasis on evidence-based reading and problem-solving. Both tests are widely accepted by colleges. AEEG offers prep for both tests so you can choose the one that best suits your strengths." },
      { question: "How long is the ACT test?", answer: "The ACT without the Writing section takes 2 hours and 55 minutes. With the optional Writing section, it takes 3 hours and 35 minutes. The test includes breaks between sections. Our prep programs include timed practice sessions to build your stamina and time management skills for test day." },
      { question: "When should I start preparing for the ACT?", answer: "We recommend starting your ACT preparation 3–6 months before your target test date. Early preparation allows for comprehensive content review, strategy development, and ample time for practice tests. AEEG offers flexible programs to fit your timeline, whether you need an intensive crash course or a longer-term study plan." },
      { question: "Does AEEG offer both in-center and online ACT prep?", answer: "Yes! AEEG offers Online Tutoring, In-Center Private Tutoring, and Online Private Tutoring programs for the ACT. Choose the format that best fits your learning style and schedule. All programs follow the same rigorous curriculum and are taught by the same expert instructors who specialize in ACT preparation." },
    ],
  },
  cta: {
    title: "Ready to Ace the ACT?",
    description: "Start your journey to a top ACT score today. Take our free diagnostic test, chat with us on WhatsApp, or visit our Cairo center to learn more.",
    buttons: { primary: "Free ACT Diagnostic", secondary: "Ask About ACT Prep" },
    note: "No commitment required. No credit card needed. Just results.",
    floatingBadge: "ACT Prep",
  },
}
