export const content = {
  hero: {
    badge: "No Hidden Fees — Pay Per Lesson",
    title: "Simple, Transparent Pricing",
    subtitle: "Choose the plan that fits your goals and budget. All tiers include expert instruction, comprehensive materials, and progress tracking. No hidden fees, no surprises.",
    ctas: { primary: "View Plans", secondary: "Book Free Consultation" },
  },
  plans: {
    badge: "Choose Your Plan",
    title: "Plans & Pricing",
    description: "Every plan includes expert American-educated tutors, proven curriculum, and flexible scheduling. Upgrade or switch anytime.",
    tiers: [
      {
        name: "Basic",
        price: 25,
        period: "per lesson",
        description: "Perfect for motivated students who thrive in a group setting with structured learning.",
        features: ["Group classes (max 6 students)", "Weekly sessions (2 hours each)", "Basic study materials included", "Email support during business hours", "Access to practice tests", "Progress tracking dashboard"],
        cta: "Get Started",
        popular: false,
      },
      {
        name: "Standard",
        price: 45,
        period: "per lesson",
        description: "Ideal for students who want personalized attention with a dedicated tutor and flexible scheduling.",
        features: ["Private 1-on-1 tutoring sessions", "Flexible scheduling (including weekends)", "All study materials & resources", "Priority email & WhatsApp support", "Full-length practice tests with scoring", "Customized study plan", "Parent progress reports"],
        cta: "Enroll Now",
        popular: true,
        badge: "Most Popular",
      },
      {
        name: "Premium",
        price: 75,
        period: "per lesson",
        description: "Our most comprehensive package for students who want unlimited access and maximum support.",
        features: ["Premium 1-on-1 tutoring sessions", "Unlimited practice tests & drills", "Weekly detailed progress reports", "Direct tutor access via WhatsApp", "Free diagnostic test included", "Score guarantee program", "College application guidance", "Priority scheduling"],
        cta: "Go Premium",
        popular: false,
        badge: "Best Value",
      },
    ],
    guarantees: [
      "2-lesson satisfaction guarantee",
      "Cancel anytime, no penalties",
      "Free trial lesson available",
    ],
  },
  additionalOptions: {
    title: "Additional Options",
    description: "Need something different? We offer specialized programs to fit unique learning needs and schedules.",
    items: [
      { title: "Subject-Only Tutoring", description: "Need help in just one area? Focus on Math, Reading, Writing, or Science without a full test prep program. Perfect for targeted improvement.", price: "From $30/lesson" },
      { title: "Intensive Bootcamps", description: "Crash courses designed for last-minute preparation. 2–4 week intensive programs with daily sessions, strategy drills, and mock exams.", price: "From $200/week" },
      { title: "Package Deals", description: "Save more when you commit to a full program. 10-lesson, 20-lesson, and 40-lesson packages available for all exam types at discounted rates.", price: "Save up to 20%" },
    ],
    cta: "Customize Your Program",
  },
  comparisonTable: {
    title: "What's Included at a Glance",
    description: "Quickly compare what each tier includes so you can choose with confidence.",
    rows: [
      { feature: "Price per lesson", basic: "$25", standard: "$45", premium: "$75" },
      { feature: "Class type", basic: "Group (max 6)", standard: "1-on-1 Private", premium: "Premium 1-on-1" },
      { feature: "Schedule flexibility", basic: "Fixed weekly", standard: "Flexible", premium: "Fully flexible" },
      { feature: "Study materials", basic: "Basic digital", standard: "All materials", premium: "All materials + extras" },
      { feature: "Practice tests", basic: "Limited access", standard: "Full access", premium: "Unlimited access" },
      { feature: "Progress reports", basic: "Dashboard only", standard: "Monthly reports", premium: "Weekly reports" },
      { feature: "Tutor access", basic: "Email only", standard: "Email + WhatsApp", premium: "Direct + priority" },
      { feature: "Free diagnostic", basic: "—", standard: "—", premium: "Included" },
      { feature: "Satisfaction guarantee", basic: "2 lessons", standard: "2 lessons", premium: "2 lessons" },
    ],
    note: "The Standard tier is our most popular choice — it offers the best balance of personalized attention and value. But if you want unlimited practice and direct tutor access, Premium is worth every penny.",
  },
  faqs: {
    badge: "Got Questions?",
    title: "Pricing FAQ",
    description: "Everything you need to know about our pricing, refunds, and packages.",
    items: [
      { question: "How does the pricing per lesson work?", answer: "You pay per lesson, and each lesson is typically 60–90 minutes depending on the program type. Group lessons are usually 2 hours. You can purchase lessons individually or in discounted packages. There are no long-term contracts — you pay as you go or upfront for packages." },
      { question: "Do you offer refunds if I'm not satisfied?", answer: "Yes! We offer a satisfaction guarantee. If after your first two lessons you're not completely satisfied, we'll refund your payment in full, no questions asked. For package deals, refunds are prorated based on lessons completed." },
      { question: "Can I switch between tiers after enrolling?", answer: "Absolutely. You can upgrade or downgrade your plan at any time. If you upgrade, we'll credit the value of your remaining lessons toward the new tier. If you downgrade, the difference can be applied to additional lessons or refunded." },
      { question: "Are there any hidden fees or registration costs?", answer: "No hidden fees whatsoever. The price you see is the price you pay. Materials are included in all tiers (Basic gets digital materials; Standard and Premium get both digital and printed). There is no registration fee, no booking fee, and no cancellation fee." },
      { question: "Do you offer sibling or group discounts?", answer: "Yes! We offer a 10% discount for siblings enrolled simultaneously. For group bookings of 3+ students (friends or classmates), we offer a 15% discount on group class rates. Contact us for details." },
      { question: "Can I get a free trial lesson before committing?", answer: "Yes! We offer a free 30-minute consultation and trial lesson for new students. This gives you a chance to meet your tutor, experience our teaching style, and discuss your goals before making any commitment." },
    ],
  },
  cta: {
    title: "Not Sure Which Plan Is Right for You?",
    description: "We're here to help you find the perfect fit. Book a free consultation with our academic advisors — no commitment, no pressure. We'll assess your goals and recommend the ideal program.",
    buttons: { primary: "Book a Free Consultation", secondary: "Chat on WhatsApp" },
  },
}
