export const content = {
  dashboard: {
    greeting: "Welcome back,",
    instructorName: "Dr. Ahmed",
    subtitle: "Here's what's happening today",
    portalName: "Practice Buddy",
    portalSubtitle: "Teacher Portal",
  },
  sidebar: {
    logo: "PB",
    brand: "Practice Buddy",
    subtitle: "Teacher Portal",
    navigation: [
      { label: "Overview", href: "/teacher", active: true },
      { label: "My Schedule", href: "/teacher/schedule" },
      { label: "My Students", href: "/teacher/students" },
      { label: "AI Tools", href: "/teacher/ai-tools", badge: "New" },
      { label: "Resources", href: "/teacher/resources" },
      { label: "Reports", href: "/teacher/reports" },
      { label: "Messages", href: "/teacher/messages", badge: "3" },
    ],
    footer: {
      whatsapp: "WhatsApp Support",
      logout: "Log Out",
    },
  },
  topBar: {
    searchPlaceholder: "Search students, classes...",
    instructorName: "Dr. Ahmed Khalil",
    instructorRole: "Senior Instructor",
  },
  stats: [
    { label: "Total Students", value: "24", trend: "+12%", trendUp: true },
    { label: "Sessions This Week", value: "14", trend: "+8%", trendUp: true },
    { label: "Upcoming Sessions", value: "6", trend: "-2%", trendUp: false },
    { label: "AI Usage", value: "89", trend: "+24%", trendUp: true },
  ],
  todaySchedule: {
    title: "Today's Schedule",
    date: "Tuesday, July 28, 2026",
    viewAll: "View All",
    items: [
      { time: "09:00 – 10:30", student: "Layla Ibrahim", course: "SAT Math Intensive", room: "Room 204", status: "completed" },
      { time: "11:00 – 12:30", student: "Omar Hassan", course: "IELTS Speaking", room: "Room 108", status: "completed" },
      { time: "13:00 – 14:30", student: "Nour El-Din", course: "ACT English Prep", room: "Room 301", status: "upcoming" },
      { time: "15:00 – 16:00", student: "Mariam Youssef", course: "TOEFL Writing", room: "Room 205", status: "upcoming" },
      { time: "17:00 – 18:30", student: "Youssef Ali", course: "SAT Math Intensive", room: "Room 204", status: "cancelled" },
      { time: "19:00 – 20:00", student: "Sara Mansour", course: "IELTS Reading", room: "Room 108", status: "upcoming" },
    ],
  },
  quickActions: {
    title: "Quick Actions",
    items: [
      { label: "Add Student", color: "hover:border-primary/30" },
      { label: "New Report", color: "hover:border-accent/30" },
      { label: "Attendance", color: "hover:border-emerald-500/30" },
      { label: "Message", color: "hover:border-blue-500/30" },
    ],
  },
  monthlyStats: {
    label: "This Month",
    value: "42",
    sublabel: "sessions completed",
    trend: "12% higher than last month",
  },
  myStudents: {
    title: "My Students",
    subtitle: "Students assigned to your courses",
    viewAll: "View All",
    columns: ["Student", "Course", "Score", "Next Session", "Progress"],
    items: [
      { name: "Layla Ibrahim", course: "SAT Math Intensive", lastScore: "720", nextSession: "Tomorrow, 9:00 AM", progress: 75 },
      { name: "Omar Hassan", course: "IELTS Speaking", lastScore: "6.5", nextSession: "Today, 11:00 AM", progress: 60 },
      { name: "Nour El-Din", course: "ACT English Prep", lastScore: "28", nextSession: "Today, 1:00 PM", progress: 85 },
      { name: "Mariam Youssef", course: "TOEFL Writing", lastScore: "24", nextSession: "Today, 3:00 PM", progress: 45 },
      { name: "Youssef Ali", course: "SAT Math Intensive", lastScore: "680", nextSession: "Cancelled", progress: 50 },
      { name: "Sara Mansour", course: "IELTS Reading", lastScore: "7.0", nextSession: "Today, 7:00 PM", progress: 90 },
      { name: "Karim Adel", course: "ACT Science Prep", lastScore: "26", nextSession: "Wed, 10:00 AM", progress: 35 },
      { name: "Donia Mostafa", course: "TOEFL Listening", lastScore: "22", nextSession: "Thu, 2:00 PM", progress: 70 },
    ],
  },
  recentActivity: {
    title: "Recent Activity",
    items: [
      { text: "Marked attendance for Layla Ibrahim — SAT Math", time: "10 min ago" },
      { text: "Submitted progress report for Omar Hassan", time: "1 hour ago" },
      { text: "Sent feedback to Nour El-Din's parents", time: "2 hours ago" },
      { text: "Sara Mansour scored 7.0 on IELTS mock test", time: "3 hours ago" },
      { text: "New student Youssef Ali enrolled in SAT Math", time: "Yesterday" },
    ],
  },
  aiTools: {
    title: "AI Teaching Assistant",
    subtitle: "Generate quizzes, plans, and more",
    buttons: ["Lesson Planner", "Quiz Generator"],
  },
  generateReports: {
    title: "Generate Progress Reports",
    description: "Create comprehensive progress reports for all your students with AI-powered insights",
    button: "Generate Reports",
  },
}